#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD socket server
# Description:       Starts the AESD socket server at boot
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket
PIDFILE=/var/run/$NAME.pid

start() {
    echo "Starting $NAME"
    start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -d
}

stop() {
    echo "Stopping $NAME"
    start-stop-daemon --stop --pidfile $PIDFILE
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
