#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DAEMON_PATH="/usr/bin/aesdsocket"
DAEMON_NAME="aesdsocket"

case "$1" in
    start)
    echo "Starting $DAEMON_NAME"
    start-stop-daemon --start --name aesdsocket --startas /usr/bin/aesdsocket -- -d
    ;;
    stop)
    echo "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --name aesdsocket
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0