#!/bin/sh

DAEMON=aesdsocket

start() {
    echo "Starting $DAEMON"
    start-stop-daemon --start --start --quiet --name $DAEMON --exec $DAEMON -- -d
}

stop() {
    echo "Stopping $DAEMON"
    start-stop-daemon --stop --quiet --name $DAEMON
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
